# Generated by Django 5.1 on 2024-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embedding',
            old_name='embedding_vector',
            new_name='embedding',
        ),
        migrations.RemoveField(
            model_name='embedding',
            name='document',
        ),
        migrations.AddField(
            model_name='embedding',
            name='asset_id',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
